use_frameworks!
platform :ios, '12.0'

target 'DVIA-v2' do
    pod 'Parse'
    pod 'GoogleAnalytics'
    pod 'RealmSwift'
    pod 'couchbase-lite-ios'
    pod 'Flurry-iOS-SDK/FlurrySDK'
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "12.0"
    end
  end
end
